name: ubuntu-latest CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, v* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:e2e